### ISSUE TITLE
Improve more advance security Settings

### ISSUE THREAD

**Issue by AnneeSam** [bootstrapguru/socialite-requests#35]

**Comment by vijaythecoder** [comment]
need more info on it

**Comment by AnneeSam** [comment]
mobile number verification

**Comment by AnneeSam** [comment]
two step verification

**Comment by vijaythecoder** [comment]
please don't spam, we have already addressed this 
https://github.com/bootstrapguru/socialite-requests/issues/34
https://github.com/bootstrapguru/socialite-requests/issues/36
