### ISSUE TITLE
Social profile icons in profile

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#40]
It would be nice if you could add the feature to show our social profile icons like fb twitter utube and instagram in our profile page or profile card.
And also to add additional profile derails like job and other details

**Comment by anusha65** [comment]
Added the social profile icons in user profile page:
![image](https://cloud.githubusercontent.com/assets/5723954/18227701/642a94a0-724b-11e6-8a66-cfe7b31e0066.png)

**Comment by rvnamb** [comment]
:+1:

**Comment by rvnamb** [comment]
What about additional profile details like hobbies,interests,job and other custom fields ?
