### ISSUE TITLE
Real time chat problem

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#45]
Sorry for submitting issues after issues.

But the chats are not getting delivered in real time,it currently requires a page refresh. Same with the notifications too.

**Comment by anusha65** [comment]
Please test thoroughly before posting anything online. As I suggested you please read the documentation and update all the third party services, You need to register on pusher and add the keys to make it work real time. and also you are testing on localhost, I really request you to read the whole documentation setup and test all the things.

**Comment by rvnamb** [comment]
Ok sorry :+1:
