### ISSUE TITLE
Messaging feature request

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#46]
Correct me if i am wrong,is there a delete button for the messages ?
And i am able to send blank messages to others. The image to which is attached below
Can you please add an attachment option for messages ?

![blank messages](https://cloud.githubusercontent.com/assets/20636487/18228743/4344392a-7279-11e6-9056-4f8062ae15e0.PNG)

**Comment by rvnamb** [comment]
A choose smiley icon button will also be a good addition

**Comment by rvnamb** [comment]
And also to move the button to open and close chat box from the notifications place to the bottom right corner or other place.

**Comment by anusha65** [comment]
Empty message is already reported and sorry we can't provide delete option for messages
