### ISSUE TITLE
Option to change default font awesome icons

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#56]
This theme looks just like Facebook now. A customization option can make it look different and unique.

**Comment by vijaythecoder** [comment]
if you know how to design and code, feel free to change the design :) it will be hard to give option to customize whole theme, we are going to release new themes once the product is good enough and have all the options requested by users. but for now there is no way to give option to change how the design looks.

**Comment by rvnamb** [comment]
Its okay..by the way your sxript looks so good. I have been using buddypress till now but im not going back as i have found your script :) but it still reqiires some features like QndA or forums and a premium memberships to join groups
