### ISSUE TITLE
Make the theme more usable

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#60]
![drop down widget](https://cloud.githubusercontent.com/assets/20636487/18235944/91b805bc-733e-11e6-87e8-92ff3b3a7ca2.PNG)
![home widget](https://cloud.githubusercontent.com/assets/20636487/18235945/920a47fa-733e-11e6-9291-4f74d69de20c.PNG)

If you can see in the image attached, we can really remove the Pages,Groups,Settings,Profile buttons from the main menu widget. They are available in the drop-down button which more practical.
If we can move the Home and Browse button to the top bar then it would be good. Just a suggestion

**Comment by anusha65** [comment]
We have done more research on UX of the design and  developed the application. We might add your requirement in the upcoming themes.Sorry, we can't modify it now.
