### ISSUE TITLE
Privacy option for pages and groups

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#65]
![groups privacy](https://cloud.githubusercontent.com/assets/20636487/18237703/3e7af274-7352-11e6-9ef4-c4d3050616de.PNG)

What if i don't want to show my created pages and groups ? I dont want others to know that i am the owner of the so and so pages and groups. As pages and groups will be having different mention names
it will be better to not show them in our profile.

**Comment by rvnamb** [comment]
Also to hide page admins from page
![admin](https://cloud.githubusercontent.com/assets/20636487/18238353/b053bc44-7359-11e6-9fda-ff98a759deea.PNG)

and provide an email id option in contact us button

**Comment by anusha65** [comment]
Your requirements seems to be customisations for your product. Yes, we are heppy to do custom work with some basic charge. Please contact us support regarding any custom requirements.
