### ISSUE TITLE
Just used the live preview of your latest version still youtube videos are not rendered

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#68]
![youtube eroor](https://cloud.githubusercontent.com/assets/20636487/18240787/71f1ecac-736b-11e6-8d3e-076fa9b76886.PNG)

**Comment by rvnamb** [comment]
They are pasted as just plain text and are not even clickable

**Comment by rvnamb** [comment]
and also duplicate posts...please disable duplicate posts..we are able to post the same thing again and again which welcomes a lot of spam activity

**Comment by anusha65** [comment]
You are not supposed to paste it directly in the post content area! There is a video icon beside music icon, you gotto click that icon which appear a new line and then you need to paste the youtue link here which will show you the video.
