### ISSUE TITLE
Message notification and other bug

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#70]
![msg error](https://cloud.githubusercontent.com/assets/20636487/18265446/6695f934-7433-11e6-9a72-ec76daf262a9.PNG)

We are getting notifications as messages which is not required and the message notifications is not cleared even after reading the message in the chat box. The notification is only cleared after we go into the message button in the main widget.

**Comment by anusha65** [comment]
It is just a real time notification that you got a message and if you click on that notification it will be dissappeared.

**Comment by rvnamb** [comment]
not that notification, the notification bubble at the top is not clearing @anusha65
