### ISSUE TITLE
Difference between main message box and chat box

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#72]
![msg lft rght](https://cloud.githubusercontent.com/assets/20636487/18265960/d44dc2d4-7435-11e6-872d-c88e266aeb7f.PNG)

if you can see in main message box all the texts are on the left side but in the chat box it is left and right according to the user. Is it possible to make the main message just as same as the chat box ? I meant left and right

**Comment by rvnamb** [comment]
and you can see the '?' and '!' are out of place when sent
and is correctly displayed on the other side

**Comment by anusha65** [comment]
Currently we can't change the design of chat box, we have many other features in our list, if you need any changes to be done, contact our support.
