### ISSUE TITLE
How does the follow suggestion works ?

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#74]
This is not a custom requirement,the follow suggestion should have a logic behind it.
It should be related ro the users profile data. If user loves music then suggest him people,pages and groups related to music.
Just think about it,its a great feature and not a custom requirement.

**Comment by anusha65** [comment]
Suggested users are the following users of the current user's following list. This is the logic, we haven't implemented it basing on the custom fields. If you need something of that sort, contact our support.
