### ISSUE TITLE
Wrong NOCAPTCHA Values in .Env file

### ISSUE THREAD

**Issue by johnsonthedev** [bootstrapguru/socialite-requests#85]
In the .env file the Captcha values are

NO_CAPTCHA_SITEKEY
NO_CAPTCHA_SECRET

This does not work for me. I needed to change it to

NOCAPTCHA_SITEKEY
NOCAPTCHA_SECRET

Is this a bug?

**Comment by anusha65** [comment]
Yeah we heard this from one of our customers, we have already fixed this in our next update.
