### ISSUE TITLE
No button to create post in new group

### ISSUE THREAD

**Issue by johnsonthedev** [bootstrapguru/socialite-requests#86]
If I create a new group the button to post new posts in the group are not visible

**Comment by johnsonthedev** [comment]
Group.php

public function membership($user_id)
    {
        $groupUser = $this->users()->where('user_id', $user_id)->first();

```
    if ($groupUser){
        $result = $groupUser->pivot->status == "approved" ? true : false;
    } else {
        $result = false;
    }

    return $result;
}
```

Timeline.blade.php
@elseif($timeline->type == "group")
                                @if(($group->post_privacy == "only_admins" && $group->is_admin(Auth::user()->id)))
                                    {!! Theme::partial('create-post',compact('timeline')) !!}
                                @elseif($group->post_privacy == "members" && $group->membership(Auth::user()->id))
                                    {!! Theme::partial('create-post',compact('timeline')) !!}
                                @endif
                            @endif

**Comment by anusha65** [comment]
You can change the settings for the group in the admin panel.
