### ISSUE TITLE
Better Javascript support

### ISSUE THREAD

**Issue by johnsonthedev** [bootstrapguru/socialite-requests#88]
It would be great if the javascript would update the aggregated counts automatically.

 e.g.
- if i like a page it still shows 0 People like this until I refresh the page. 
- if I follow a person from suggested page the following count does not get updated until page refresh

**Comment by rvnamb** [comment]
Please +1 issues submitted by me if they seems like needed features so that they will consider that too

**Comment by anusha65** [comment]
We are using Jquery for the application and for few we used Vue.js so we have a plan to implement Vue.js for every module and yeah we are working on it :)
