### ISSUE TITLE
suggested box. actions take very long

### ISSUE THREAD

**Issue by johnsonthedev** [bootstrapguru/socialite-requests#89]
When i follow/unfollow a person from the suggested Person box it takes extremely long.

Like /unlike of a comment or writing a reply to a comments is fast. So it has nothing to do with my environment. 

Have you heard this from someone else too ?

**Comment by anusha65** [comment]
We haven't heard this from anyone, but yeah we will check it again and if there is an issue we will fix this in our upcoming update
